#!/bin/sh

# xinitrc runs automatically when you run startx.

# There are some small but important commands that need to be run when we start
# the graphical environment. There is a link to this file in ~/.xprofile
# because that file is run automatically if someone uses a display manager
# (login screen) and so they are needed there. To prevent doubling up commands,
# I source them here with the line below.

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

function dwm_startup {
mpd &			# music player daemon-you might prefer it as a service though
remaps &		# run the remaps script, switching caps/esc and more; check it for more info
setbg &			# set the background with the `setbg` script
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &	# Uncomment to use Xresources colors/settings on startup
xcompmgr &		# xcompmgr for transparency
dunst &			# dunst for notifications
unclutter &		# Remove mouse when idle
xset r rate 300 50 &	# Speed xrate up
ssh-agent dwm
}

function xfce_startup {
remaps &		# run the remaps script, switching caps/esc and more; check it for more info
unclutter &		# Remove mouse when idle
xset r rate 300 50 &	# Speed xrate up
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &	# Uncomment to use Xresources colors/settings on startup
exec startxfce4
}

case $1 in
    dwm)
	dwm_startup;;
    xfce)
	xfce_startup;;
    # No known session, try to run it as command
    *) exec $1;;
esac

# This line autostarts an instance of Pulseaudio that does not exit on idle.
# This is "necessary" on Artix due to a current bug between PA and
# Chromium-based browsers where they fail to start PA and use dummy output.
#pidof -s runit &&
#	! pidof -s pulseaudio >/dev/null 2>&1 &&
#	setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1

#if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
#	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
#else
#	. "$HOME/.xprofile"
#fi

#ssh-agent dwm
